spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notify-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      host: db_mongo
      port: 27017
      database: api-jwt-docker-messaging
  main:
    lazy-initialization: false
server:
  port: 8081